/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TableIndexImport } from './routes/table/index'
import { Route as TableTableIdRouteImport } from './routes/table/$tableId/route'
import { Route as TableAddTaskIndexImport } from './routes/table/addTask/index'
import { Route as TableAddTableIndexImport } from './routes/table/addTable/index'
import { Route as TableTableIdIndexImport } from './routes/table/$tableId/index'
import { Route as TableTableIdEditImport } from './routes/table/$tableId/edit'
import { Route as TableTableIdTaskIdIndexImport } from './routes/table/$tableId/$taskId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TableIndexRoute = TableIndexImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRoute,
} as any)

const TableTableIdRouteRoute = TableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRoute,
} as any)

const TableAddTaskIndexRoute = TableAddTaskIndexImport.update({
  id: '/table/addTask/',
  path: '/table/addTask/',
  getParentRoute: () => rootRoute,
} as any)

const TableAddTableIndexRoute = TableAddTableIndexImport.update({
  id: '/table/addTable/',
  path: '/table/addTable/',
  getParentRoute: () => rootRoute,
} as any)

const TableTableIdIndexRoute = TableTableIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableTableIdRouteRoute,
} as any)

const TableTableIdEditRoute = TableTableIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TableTableIdRouteRoute,
} as any)

const TableTableIdTaskIdIndexRoute = TableTableIdTaskIdIndexImport.update({
  id: '/$taskId/',
  path: '/$taskId/',
  getParentRoute: () => TableTableIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableIndexImport
      parentRoute: typeof rootRoute
    }
    '/table/$tableId/edit': {
      id: '/table/$tableId/edit'
      path: '/edit'
      fullPath: '/table/$tableId/edit'
      preLoaderRoute: typeof TableTableIdEditImport
      parentRoute: typeof TableTableIdRouteImport
    }
    '/table/$tableId/': {
      id: '/table/$tableId/'
      path: '/'
      fullPath: '/table/$tableId/'
      preLoaderRoute: typeof TableTableIdIndexImport
      parentRoute: typeof TableTableIdRouteImport
    }
    '/table/addTable/': {
      id: '/table/addTable/'
      path: '/table/addTable'
      fullPath: '/table/addTable'
      preLoaderRoute: typeof TableAddTableIndexImport
      parentRoute: typeof rootRoute
    }
    '/table/addTask/': {
      id: '/table/addTask/'
      path: '/table/addTask'
      fullPath: '/table/addTask'
      preLoaderRoute: typeof TableAddTaskIndexImport
      parentRoute: typeof rootRoute
    }
    '/table/$tableId/$taskId/': {
      id: '/table/$tableId/$taskId/'
      path: '/$taskId'
      fullPath: '/table/$tableId/$taskId'
      preLoaderRoute: typeof TableTableIdTaskIdIndexImport
      parentRoute: typeof TableTableIdRouteImport
    }
  }
}

// Create and export the route tree

interface TableTableIdRouteRouteChildren {
  TableTableIdEditRoute: typeof TableTableIdEditRoute
  TableTableIdIndexRoute: typeof TableTableIdIndexRoute
  TableTableIdTaskIdIndexRoute: typeof TableTableIdTaskIdIndexRoute
}

const TableTableIdRouteRouteChildren: TableTableIdRouteRouteChildren = {
  TableTableIdEditRoute: TableTableIdEditRoute,
  TableTableIdIndexRoute: TableTableIdIndexRoute,
  TableTableIdTaskIdIndexRoute: TableTableIdTaskIdIndexRoute,
}

const TableTableIdRouteRouteWithChildren =
  TableTableIdRouteRoute._addFileChildren(TableTableIdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table/$tableId': typeof TableTableIdRouteRouteWithChildren
  '/table': typeof TableIndexRoute
  '/table/$tableId/edit': typeof TableTableIdEditRoute
  '/table/$tableId/': typeof TableTableIdIndexRoute
  '/table/addTable': typeof TableAddTableIndexRoute
  '/table/addTask': typeof TableAddTaskIndexRoute
  '/table/$tableId/$taskId': typeof TableTableIdTaskIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/table': typeof TableIndexRoute
  '/table/$tableId/edit': typeof TableTableIdEditRoute
  '/table/$tableId': typeof TableTableIdIndexRoute
  '/table/addTable': typeof TableAddTableIndexRoute
  '/table/addTask': typeof TableAddTaskIndexRoute
  '/table/$tableId/$taskId': typeof TableTableIdTaskIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/table/$tableId': typeof TableTableIdRouteRouteWithChildren
  '/table/': typeof TableIndexRoute
  '/table/$tableId/edit': typeof TableTableIdEditRoute
  '/table/$tableId/': typeof TableTableIdIndexRoute
  '/table/addTable/': typeof TableAddTableIndexRoute
  '/table/addTask/': typeof TableAddTaskIndexRoute
  '/table/$tableId/$taskId/': typeof TableTableIdTaskIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/table/$tableId'
    | '/table'
    | '/table/$tableId/edit'
    | '/table/$tableId/'
    | '/table/addTable'
    | '/table/addTask'
    | '/table/$tableId/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/table'
    | '/table/$tableId/edit'
    | '/table/$tableId'
    | '/table/addTable'
    | '/table/addTask'
    | '/table/$tableId/$taskId'
  id:
    | '__root__'
    | '/'
    | '/table/$tableId'
    | '/table/'
    | '/table/$tableId/edit'
    | '/table/$tableId/'
    | '/table/addTable/'
    | '/table/addTask/'
    | '/table/$tableId/$taskId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableTableIdRouteRoute: typeof TableTableIdRouteRouteWithChildren
  TableIndexRoute: typeof TableIndexRoute
  TableAddTableIndexRoute: typeof TableAddTableIndexRoute
  TableAddTaskIndexRoute: typeof TableAddTaskIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableTableIdRouteRoute: TableTableIdRouteRouteWithChildren,
  TableIndexRoute: TableIndexRoute,
  TableAddTableIndexRoute: TableAddTableIndexRoute,
  TableAddTaskIndexRoute: TableAddTaskIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/table/$tableId",
        "/table/",
        "/table/addTable/",
        "/table/addTask/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/table/$tableId": {
      "filePath": "table/$tableId/route.tsx",
      "children": [
        "/table/$tableId/edit",
        "/table/$tableId/",
        "/table/$tableId/$taskId/"
      ]
    },
    "/table/": {
      "filePath": "table/index.tsx"
    },
    "/table/$tableId/edit": {
      "filePath": "table/$tableId/edit.tsx",
      "parent": "/table/$tableId"
    },
    "/table/$tableId/": {
      "filePath": "table/$tableId/index.tsx",
      "parent": "/table/$tableId"
    },
    "/table/addTable/": {
      "filePath": "table/addTable/index.tsx"
    },
    "/table/addTask/": {
      "filePath": "table/addTask/index.tsx"
    },
    "/table/$tableId/$taskId/": {
      "filePath": "table/$tableId/$taskId/index.tsx",
      "parent": "/table/$tableId"
    }
  }
}
ROUTE_MANIFEST_END */
